title: Geometry-First Foundations of the Finite Element Method
description: Foundational notes developing an operator-theoretic, geometry-first formulation of the Finite Element Method.

theme: just-the-docs

url: "https://haridev-v.github.io"
baseurl: "/geometry-first-fem"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-include-cache

  aux_links_new_tab: true

