title: Geometry-First FEM
description: Operator-theoretic finite element notes

theme: just-the-docs

url: "https://haridev-v.github.io"
baseurl: "/geometry-first-fem"

markdown: kramdown

kramdown:
  math_engine: mathjax

plugins:
  - jekyll-include-cache

search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
