logo: "/figures/logo.svg"
title: Geometric foundations of FEM
description: Foundational notes developing an operator-theoretic, geometry-first formulation of the Finite Element Method.
title_separator: "â€”"


theme: just-the-docs

url: "https://haridev-v.github.io"
baseurl: "/geometry-first-fem"

markdown: kramdown

kramdown:
  math_engine: mathjax

plugins:
  - jekyll-include-cache

search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"
nav_external_links_new_tab: true
nav_external_links: false
nav_sort: case_sensitive
nav_enabled: true
nav_show_all: true
nav_show_all: true
nav_next_prev: true

color_scheme: ink
aux_links:
  "Home":
    - "/geometry-first-fem/"

