title: Geometry-First FEM
description: Operator-theoretic finite element notes

remote_theme: just-the-docs/just-the-docs

markdown: kramdown

kramdown:
  math_engine: mathjax

plugins:
  - jekyll-remote-theme
